# GeoIP.conf file for `geoipupdate` program, for versions >= 3.1.1.
# Used to update GeoIP databases from https://www.maxmind.com.
# For more information about this config file, visit the docs at
# https://dev.maxmind.com/geoip/updating-databases.

# `AccountID` is from your MaxMind account.
AccountID 1227954

# `LicenseKey` is from your MaxMind account.
LicenseKey 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

# `EditionIDs` is from your MaxMind account.
# 中国被禁止下载 GeoLite2-City
# EditionIDs GeoLite2-ASN GeoLite2-City GeoLite2-Country
EditionIDs GeoLite2-ASN GeoLite2-Country
